version: "3"
services:
    nginx:
        tty: true
        image: nginx:alpine
        container_name: multipurpose-admin-panel
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/nginx/ssl:/etc/nginx/config.d/ssl
        links:
            - php
        depends_on:
            - php
        networks:
            - admin-panel-network
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: multipurpose-admin-panel-php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html:cached
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ~/.ssh:/root/.ssh
        depends_on:
            - redis
            - mysql
        networks:
            - admin-panel-network

    mysql:
        image: "mysql/mysql-server:8.0"
        container_name: multipurpose-admin-panel-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: admin_panel
            MYSQL_USER: admin_panel
            MYSQL_PASSWORD: admin_panel
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - admin-panel-network
    redis:
        image: redis:alpine
        container_name: multipurpose-admin-panel-redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
        networks:
            - admin-panel-network

volumes:
    db_data:
        driver: "local"
    cache_data:
        driver: "local"
    admin-panel-volumen:
        driver: "local"

networks:
    admin-panel-network:
        driver: "bridge"
